---
hwr_fpm_pools:
    - name: default
      user: "{{ hwr_http_user }}"
      group: "{{ hwr_http_user_group }}"
      listen: 8000
      listen.allowed_clients: "127.0.0.1"
      listen.owner: "{{ hwr_http_user }}"
      listen.group: "{{ hwr_http_user_group }}"
      chdir: "/var/www/default"
      pm: dynamic
      pm.max_children: 10
      pm.start_servers: 2
      pm.min_spare_servers: 2
      pm.max_spare_servers: 5
      pm.process_idle_timeout: "10s"
      pm.max_requests: 0
      pm.status_path: "/status"
      access.log: "/var/log/default.access.log"
      access.format: "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"

nginx_sites:
  default:
    - "listen 80"
    - "server_name localhost"
    - "root /var/www/default"
    - "location / {
      root /var/www/default;
      include fastcgi_params;
      fastcgi_pass 127.0.0.1:8000;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }"

# ex: ft=ansible et ts=2 sw=2
